name: Deploy from Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy from Docker Hub
        run: |
          docker pull your-docker-registry/myapp:latest
          docker run -d -p 8080:8080 your-docker-registry/myapp:latest
