name: Deploy using Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy-helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.x

      - name: Deploy using Helm
        run: |
          helm upgrade --install myapp ./path/to/myapp-chart --namespace default
