name: Terraform GKE Cluster and Helm Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.x

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Terraform Init and Apply
        run: |
          cd path/to/terraform/code
          terraform init
          terraform apply -auto-approve

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.x

      - name: Helm Deployment
        run: |
          kubectl config use-context ${{ secrets.KUBE_CONTEXT }}
          helm upgrade --install myapp ./path/to/myapp-chart --namespace default
