name: Encrypt Kube Config

on:
  push:
    branches:
      - main

jobs:
  encrypt-kube-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Encrypt and store kubeconfig
        run: |
          # Read kubeconfig file
          KUBE_CONFIG_CONTENT=$(cat $HOME/.kube/config)

          # Encrypt kubeconfig content using base64
          ENCRYPTED_KUBE_CONFIG=$(echo "$KUBE_CONFIG_CONTENT" | base64)

          # Store the encrypted kubeconfig as a secret
          echo "$ENCRYPTED_KUBE_CONFIG" | tr -d '\n' > encrypted_kube_config.txt
          echo "KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}" >> $GITHUB_ENV
          echo "ENCRYPTED_KUBE_CONFIG: $ENCRYPTED_KUBE_CONFIG" >> $GITHUB_ENV

      - name: Upload encrypted kubeconfig as a secret
        uses: actions/upload-artifact@v2
        with:
          name: encrypted-kubeconfig
          path: encrypted_kube_config.txt
